---
defaults: &defaults
  alpha: null
  background: null
  define: null
  density: null
  extent: null
  gravity: null
  resize: null
  scale: null
.svg:
  .png:
    <<: *defaults
    background: :background
    density: :max
    extent: :auto
    gravity: center
    scale: :auto
  .ico:
    <<: *defaults
    background: :background
    define:
      icon:
        auto-resize: :auto
    density: :max
    extent: :auto
    gravity: center
    scale: :max
  .svg:
    <<: *defaults
.png:
  .ico:
    <<: *defaults
    background: :background
    define:
      icon:
        auto-resize: :auto
    extent: :auto
    gravity: center
    resize: :max
  .png:
    <<: *defaults
    background: :background
    extent: :auto
    gravity: center
    resize: :max
