---
link:
  as: null
  color: null
  crossorigin: null
  disabled: null
  href: null
  hreflang: null
  imagesizes: null
  imagesrcset: null
  media: null
  prefetch: null
  rel: null
  sizes: null
  title: null
  type: null
meta:
  charset: null
  content: null
  http-equiv: null
  itemprop: null
  name: null
