Metrics/BlockLength:
  Exclude:
    - Rakefile
    - !ruby/regexp /_test\.rb$/
Metrics/ModuleLength:
  Exclude:
    - !ruby/regexp /_test\.rb$/
Naming/FileName:
  Exclude:
    - lib/jekyll-favicon.rb
Style/AndOr:
  EnforcedStyle: conditionals
