---
source:
  name: favicon.svg
  dir: .
background: transparent
dir: .
assets:
  - name: favicon.ico
    convert:
      define: 'icon:auto-resize=36,24,16'
      scale: 36x36
    tag:
      - link:
          href: :url
          rel: shortcut icon
          type: :mime
          sizes: :sizes
  - name: favicon.png
    convert:
      scale: 196x196
    tag:
      - link:
          href: :url
          rel: icon
          type: :mime
          sizes: :sizes
  - name: apple-touch-icon.png
    convert:
      scale: 180x180
  - name: safari-pinned-tab.svg
    tag:
      - link:
          color: :background
          href: :url
          rel: mask-icon
  - name: android-chrome-192x192.png
    convert:
      scale: 192x192
    refer:
      - webmanifest:
          icons:
          - src: :url
  - name: android-chrome-512x512.png
    convert:
      scale: 512x512
    refer:
      - webmanifest:
          icons:
          - src: :url
  - name: mstile-icon-128x128.png
    convert:
      scale: 128x128
    refer:
      - browserconfig:
          msapplication:
            tile:
              TileColor:
                __text: :background
              square70x70logo:
                _src: :url
    tag:
      - meta:
          content: :url
          name: msapplication-TileImage
      - meta:
          content: :background
          name: msapplication-TileColor

  - name: mstile-icon-270x270.png
    convert:
      scale: 270x270
    refer:
      - browserconfig:
          msapplication:
            tile:
              TileColor:
                __text: :background
              square150x150logo:
                _src: :url
  - name: mstile-icon-558x270.png
    convert:
      scale: 558x270
    refer:
      - browserconfig:
          msapplication:
            tile:
              TileColor:
                __text: :background
              wide310x150logo:
                _src: :url
  - name: mstile-icon-558x558.png
    convert:
      scale: 558x558
    refer:
      - browserconfig:
          msapplication:
            tile:
              TileColor:
                __text: :background
              square310x310logo:
                _src: :url
  - name: manifest.webmanifest
    source:
      name: manifest.webmanifest
    tag:
      - link:
          href: :url
          rel: manifest
  - name: browserconfig.xml
    source:
      name: browserconfig.xml
    tag:
      - meta:
          content: :url
          name: msapplication-config
