# rubocop:disable Naming/FileName
# rubocop:enable Naming/FileName
require 'jekyll'
require 'mini_magick'
require_relative 'string'
require_relative 'hash'
require_relative 'browserconfig'
require_relative 'webmanifest'
require_relative 'image'
require_relative 'jekyll/favicon'
require_relative 'jekyll/favicon/version'
require_relative 'jekyll/favicon/hooks'
require_relative 'jekyll/favicon/metadata'
require_relative 'jekyll/favicon/icon'
require_relative 'jekyll/favicon/generator'
require_relative 'jekyll/favicon/tag'
